#!/usr/bin/env node
// Validate a Profound UI Rich Display File against the structured property
// catalog. Checks property names per widget, required structural fields,
// id uniqueness, and layout/grid reference targets.
//
// Usage:  node validate-rdf.mjs <path-to-rdf.json>
// Exit:   0 on clean validation, 1 on errors, 2 on bad invocation/parse failure.

import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const CATALOG_PATH = path.resolve(__dirname, "..", "reference", "properties.json");
const EXTENSIONS_PATH = path.resolve(__dirname, "..", "reference", "catalog-extensions.json");

const args = process.argv.slice(2);
if (args.length !== 1) {
  console.error("Usage: validate-rdf.mjs <path-to-rdf.json>");
  process.exit(2);
}
const rdfPath = args[0];

let rdf;
try {
  rdf = JSON.parse(readFileSync(rdfPath, "utf8"));
} catch (e) {
  console.error(`Cannot parse ${rdfPath}: ${e.message}`);
  process.exit(2);
}

const catalog = JSON.parse(readFileSync(CATALOG_PATH, "utf8"));
// Merge catalog extensions (manual additions for widgets/properties not in
// the autogenerated catalog — e.g. PLS custom widget kits).
let extensions = { widgets: [], properties: {} };
try {
  extensions = JSON.parse(readFileSync(EXTENSIONS_PATH, "utf8"));
} catch { /* extensions file is optional */ }
for (const w of extensions.widgets || []) {
  if (!catalog.widgets.includes(w)) catalog.widgets.push(w);
}
for (const [name, def] of Object.entries(extensions.properties || {})) {
  if (!catalog.properties[name]) catalog.properties[name] = def;
  else {
    // Extend appliesTo with any extras from extensions
    const ext = def.appliesTo;
    const cur = catalog.properties[name].appliesTo;
    if (Array.isArray(ext) && Array.isArray(cur)) {
      for (const w of ext) if (!cur.includes(w)) cur.push(w);
    }
  }
}

const KNOWN_WIDGETS = new Set(catalog.widgets);
const UNIVERSAL = new Set(
  Object.entries(catalog.properties)
    .filter(([, def]) => def.appliesTo === "*")
    .map(([name]) => name),
);
// Properties marked multOccur in the catalog can appear as "<name> 2",
// "<name> 3", ..., per the designer's "Add Another <Prop>" pattern.
const MULT_OCCUR_BASES = new Set(
  Object.entries(catalog.properties)
    .filter(([, def]) => def.multOccur)
    .map(([name]) => name),
);
// Map widget -> Set of widget-specific properties
const WIDGET_PROPS = new Map();
for (const w of catalog.widgets) WIDGET_PROPS.set(w, new Set());
for (const [name, def] of Object.entries(catalog.properties)) {
  if (Array.isArray(def.appliesTo)) {
    for (const w of def.appliesTo) {
      if (WIDGET_PROPS.has(w)) WIDGET_PROPS.get(w).add(name);
    }
  }
}

function multOccurBaseFor(key) {
  const m = /^(.+) (\d+)$/.exec(key);
  if (!m) return null;
  const base = m[1];
  const n = Number(m[2]);
  if (n < 2) return null;
  return MULT_OCCUR_BASES.has(base) ? base : null;
}

// Properties allowed on every item regardless of widget — the "binding" /
// containment / runtime keys that aren't in the property catalog but are
// part of the RDF file shape.
const ITEM_STRUCTURAL = new Set([
  "id",
  "field type",
  "layout",
  "container",
  "grid",
  "column",
  // Properties that are widget-specific in the catalog but, in practice,
  // appear universally in real files because the runtime accepts them on
  // any item. None known at this layer — extend if false positives appear.
]);

const errors = [];
const warnings = [];

function err(loc, msg) { errors.push(`[error] ${loc}: ${msg}`); }
function warn(loc, msg) { warnings.push(`[warn]  ${loc}: ${msg}`); }

// -------- Top-level --------

if (typeof rdf !== "object" || rdf === null || Array.isArray(rdf)) {
  err("/", "root must be a JSON object");
  report();
}

if (typeof rdf.text !== "string") err("/text", `must be a string, got ${typeOf(rdf.text)}`);
if (!Array.isArray(rdf.formats)) err("/formats", `must be an array, got ${typeOf(rdf.formats)}`);
else if (rdf.formats.length === 0) err("/formats", "must contain at least one format");

if (rdf.keywords !== undefined && !Array.isArray(rdf.keywords))
  err("/keywords", `must be an array of strings, got ${typeOf(rdf.keywords)}`);
if (rdf["long name aliases"] !== undefined && typeof rdf["long name aliases"] !== "boolean")
  err("/long name aliases", `must be a real JSON boolean (true/false), got ${typeOf(rdf["long name aliases"])}`);

// -------- Per format --------

const idsByFormat = []; // [Set of ids per format]

if (Array.isArray(rdf.formats)) {
  rdf.formats.forEach((fmt, fi) => {
    const fmtLoc = `/formats[${fi}]`;
    if (typeof fmt !== "object" || fmt === null) {
      err(fmtLoc, "must be an object");
      return;
    }
    const screen = fmt.screen;
    if (typeof screen !== "object" || screen === null) {
      err(`${fmtLoc}/screen`, "must be an object");
    } else {
      if (typeof screen["record format name"] !== "string" || screen["record format name"].length === 0) {
        err(`${fmtLoc}/screen/record format name`, "required, must be a non-empty string");
      }
      if (screen.overlay !== undefined && !["true", "false"].includes(screen.overlay)) {
        err(`${fmtLoc}/screen/overlay`, `must be the string "true" or "false" (not real boolean)`);
      }
      if (screen["overlay range"] !== undefined && !/^\d+-\d+$/.test(screen["overlay range"])) {
        err(`${fmtLoc}/screen/overlay range`, `must look like "<startRow>-<endRow>", got ${JSON.stringify(screen["overlay range"])}`);
      }
    }

    const items = fmt.items;
    if (!Array.isArray(items)) {
      err(`${fmtLoc}/items`, `must be an array, got ${typeOf(items)}`);
      idsByFormat.push(new Set());
    } else {
      const fmtIds = new Set();
      idsByFormat.push(fmtIds);
      items.forEach((it, ii) => {
        const itLoc = `${fmtLoc}/items[${ii}]`;
        validateItem(it, itLoc, fmtIds);
      });
    }

    // dspf record layout (optional but present in real files)
    const layout = fmt["dspf record layout"];
    if (layout !== undefined) {
      if (typeof layout !== "object" || layout === null || Array.isArray(layout)) {
        err(`${fmtLoc}/dspf record layout`, `must be an object mapping record-format-name -> array of buffer entries`);
      } else {
        for (const [fmtName, entries] of Object.entries(layout)) {
          const lLoc = `${fmtLoc}/dspf record layout/${fmtName}`;
          if (!Array.isArray(entries)) {
            err(lLoc, "must be an array of buffer-field entries");
            continue;
          }
          entries.forEach((e, ei) => {
            const eLoc = `${lLoc}[${ei}]`;
            if (typeof e !== "object" || e === null) {
              err(eLoc, "must be an object");
              return;
            }
            if (typeof e.name !== "string" || e.name.length === 0) err(`${eLoc}/name`, "required, non-empty string");
            if (e.inBufPos !== undefined && (!Number.isInteger(e.inBufPos) || e.inBufPos < 1))
              err(`${eLoc}/inBufPos`, `must be a positive integer if present`);
            if (e.outBufPos !== undefined && (!Number.isInteger(e.outBufPos) || e.outBufPos < 1))
              err(`${eLoc}/outBufPos`, `must be a positive integer if present`);
            if (e.inBufPos === undefined && e.outBufPos === undefined)
              warn(eLoc, "neither inBufPos nor outBufPos provided — field will have no buffer position");
          });
        }
      }
    }
  });
}

// -------- Layout/grid reference resolution (cross-item) --------

if (Array.isArray(rdf.formats)) {
  rdf.formats.forEach((fmt, fi) => {
    if (!Array.isArray(fmt.items)) return;
    const ids = idsByFormat[fi];
    fmt.items.forEach((it, ii) => {
      if (typeof it !== "object" || it === null) return;
      const itLoc = `/formats[${fi}]/items[${ii}]`;
      if (it.layout !== undefined && !ids.has(it.layout))
        err(`${itLoc}/layout`, `references unknown item id "${it.layout}" in same format`);
      if (it.grid !== undefined && !ids.has(it.grid))
        err(`${itLoc}/grid`, `references unknown item id "${it.grid}" in same format`);
    });
  });
}

report();

// -------- helpers --------

function validateItem(item, loc, fmtIds) {
  if (typeof item !== "object" || item === null || Array.isArray(item)) {
    err(loc, "must be an object");
    return;
  }
  if (typeof item.id !== "string" || item.id.length === 0) {
    err(`${loc}/id`, "required, non-empty string");
  } else {
    if (fmtIds.has(item.id)) err(`${loc}/id`, `duplicate id "${item.id}" in this format`);
    fmtIds.add(item.id);
    // Cross-format id reuse is the standard PUI pattern (every format has
    // its own btnSubmit/btnExit/etc.). Don't warn — only within-format
    // duplicates are real bugs.
  }

  const fieldType = item["field type"];
  if (typeof fieldType !== "string" || fieldType.length === 0) {
    err(`${loc}/field type`, "required, non-empty string");
    return;
  }
  if (!KNOWN_WIDGETS.has(fieldType)) {
    err(`${loc}/field type`, `"${fieldType}" is not a known widget type. Known: ${[...KNOWN_WIDGETS].join(", ")}`);
    return;
  }

  // Validate property names against catalog for this widget
  const specific = WIDGET_PROPS.get(fieldType);
  for (const key of Object.keys(item)) {
    if (ITEM_STRUCTURAL.has(key)) continue;
    if (UNIVERSAL.has(key)) continue;
    if (specific.has(key)) continue;
    // Multi-occurrence variant?  "css class 2" is valid if "css class"
    // exists for this widget with multOccur=true.
    const base = multOccurBaseFor(key);
    if (base && (UNIVERSAL.has(base) || specific.has(base))) continue;
    warn(`${loc}/${escapeKey(key)}`, `property "${key}" is not in the catalog for "${fieldType}" — the runtime will silently ignore it. Check spelling and widget type.`);
  }

  // container/column should be strings (we encode numbers as strings)
  if (item.container !== undefined && typeof item.container !== "string")
    warn(`${loc}/container`, `should be a string (e.g. "1"), got ${typeOf(item.container)}`);
  if (item.column !== undefined && typeof item.column !== "string")
    warn(`${loc}/column`, `should be a string (e.g. "0"), got ${typeOf(item.column)}`);
}

function escapeKey(k) { return k.replace(/\//g, "~1"); }

function typeOf(v) {
  if (v === null) return "null";
  if (Array.isArray(v)) return "array";
  return typeof v;
}

function report() {
  for (const w of warnings) console.log(w);
  for (const e of errors) console.log(e);
  console.log("");
  console.log(`Validated: ${rdfPath}`);
  console.log(`  Errors:   ${errors.length}`);
  console.log(`  Warnings: ${warnings.length}`);
  process.exit(errors.length ? 1 : 0);
}
